# Generated by Django 3.2.5 on 2021-07-17 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medico',
            unique_together={('nome', 'sobrenome', 'data_admissao')},
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=30)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('nome', 'rua', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medico')),
            ],
            options={
                'unique_together': {('data', 'medico')},
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medico')),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.posto')),
            ],
            options={
                'unique_together': {('data', 'medico')},
            },
        ),
    ]
