# Generated by Django 3.2.5 on 2021-07-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210716_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='idade',
        ),
    ]
