# Generated by Django 3.2.5 on 2021-07-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cad_postos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cad_postos',
            new_name='Cad_posto',
        ),
    ]
