# Generated by Django 3.2.5 on 2021-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cad_postos_cad_posto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_folga_semanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dia_da_semana', models.CharField(max_length=3)),
            ],
        ),
    ]
