# Generated by Django 3.2.5 on 2021-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cad_manual_escalas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cad_medico',
            name='deletar',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
