# Generated by Django 3.2.5 on 2021-07-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cad_medico_deletar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_posto',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
