# Generated by Django 3.2.5 on 2021-07-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cad_posto_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletar', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cad_medico',
            name='deletar',
        ),
    ]
