# Generated by Django 3.2.5 on 2021-07-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cad_medico_deletar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cad_medico',
            name='deletar',
        ),
        migrations.AddField(
            model_name='cad_medico',
            name='disponivel',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Parametro',
        ),
    ]
