# Generated by Django 3.2.5 on 2021-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210708_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='cad_folga_semanal',
            name='disponivel',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cad_posto',
            name='disponivel',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
