# Generated by Django 3.2.5 on 2021-07-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210708_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_folga_semanal',
            name='disponivel',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cad_medico',
            name='disponivel',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cad_posto',
            name='disponivel',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
