# Generated by Django 3.2.5 on 2021-07-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210708_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cad_medico',
            new_name='Medico',
        ),
    ]
