# Generated by Django 3.2.5 on 2021-07-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_cad_medico_medico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cad_posto',
            new_name='Posto',
        ),
    ]
