# Generated by Django 3.2.5 on 2021-07-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_cad_posto_posto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cad_folga_semanal',
            new_name='Folga',
        ),
    ]
