# Generated by Django 3.2.5 on 2021-07-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_cad_folga_semanal_folga'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cad_manual_escalas',
            new_name='Escala',
        ),
    ]
