# Generated by Django 3.2.5 on 2021-07-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_cad_manual_escalas_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
