# Generated by Django 3.2.5 on 2021-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_posto_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
