# Generated by Django 3.2.5 on 2021-07-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_escala_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.folga'),
        ),
    ]
