# Generated by Django 3.2.5 on 2021-07-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_escala_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folga',
            unique_together={('data', 'medico')},
        ),
    ]
