# Generated by Django 3.2.5 on 2021-07-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_escala_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('data', 'posto', 'medico')},
        ),
    ]
