# Generated by Django 3.2.5 on 2021-07-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_escala_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('data', 'medico')},
        ),
    ]
