# Generated by Django 3.2.5 on 2021-07-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_escala_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
