# Generated by Django 3.2.5 on 2021-07-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_escala_disponivel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medico',
            unique_together={('nome', 'sobrenome', 'data_admissao')},
        ),
    ]
