# Generated by Django 3.2.5 on 2021-07-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_medico_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posto',
            unique_together={('nome', 'rua', 'numero')},
        ),
    ]
